@startuml
actor User
User->Login: login()
activate Login
Login--> User
deactivate Login
|||
User->>TradingMain: bookTrade(Asset)
Activate TradingMain
TradingMain->>Market: bookTrade(Asset)
deactivate TradingMain
activate Market
Market->>TradingMain
activate TradingMain
deactivate Market
|||
TradingMain->TradingMain: saveTradeDetails
activate TradingMain
TradingMain->TradeDAL: saveTradeDetails
database DB
TradeDAL->DB: saveTradeDetails
DB-->TradeDAL
TradeDAL-->TradingMain
|||
deactivate TradingMain
deactivate TradingMain


@enduml
